spring.application.name=ContentWiz


content.root-directory=



youtube.upload-base=
youtube.token-url=

content.types.motivation.youtube.client-id=
content.types.motivation.youtube.client-secret=
content.types.motivation.youtube.refresh-token=
content.types.motivation.youtube.channel-id=
content.types.motivation.youtube.privacy-status=      # public | private | unlisted
content.types.motivation.youtube.category-id=            # 22=People&Blogs, 28=Science&Tech


server.port=
ngrok.auth.token=
content.types.motivation.youtube.default-category-id=

instagram.graph-base=
instagram.max-poll-attempts=

content.types.motivation.instagram.business-account-id=
content.types.motivation.instagram.access-token=